<a href="https://colab.research.google.com/github/Raden616Rizki/03_praktikum_web_lanjut_dua/blob/master/electreIV_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import math

# Penentuan Sampel
tabel_data = np.array([[5, 3, 3, 3], [4, 4, 3, 4], [4, 4, 3, 3], [2, 4, 3, 3]])

tabel_data

array([[5, 3, 3, 3],
       [4, 4, 3, 4],
       [4, 4, 3, 3],
       [2, 4, 3, 3]])

In [57]:
# Penentuan Bobot
bobot = np.array([5, 2, 4, 2])
bobot

array([5, 2, 4, 2])

In [58]:
# Normalisasi Matriks Alternatif
def normalisasi_matriks(matriks):
  baris = len(matriks)
  kolom = len(matriks[0])
  list_pembagi = []

  matriks_ternomalisasi = np.zeros((baris, kolom))

  # Memperoleh nilai pembagi yang dikuadratkan
  for k in range(kolom):
    list_pembagi.append([])
    for l in range(baris):
      list_pembagi[k].append(matriks[l][k]**2)

  for i in range(baris):
    for j in range(kolom):
      matriks_ternomalisasi[i][j] = matriks[i][j]/math.sqrt(sum(list_pembagi[j]))

  return np.array(matriks_ternomalisasi)

matriks_ternomalisasi = normalisasi_matriks(tabel_data)
matriks_ternomalisasi


array([[0.6401844 , 0.39735971, 0.5       , 0.45749571],
       [0.51214752, 0.52981294, 0.5       , 0.60999428],
       [0.51214752, 0.52981294, 0.5       , 0.45749571],
       [0.25607376, 0.52981294, 0.5       , 0.45749571]])

In [59]:
# Pembobotan pada matriks yang telah dinormalisasi
def pembobotan_matriks(matriks):
  baris = len(matriks)
  kolom = len(matriks[0])

  pembobotan_matriks = np.zeros((baris, kolom))

  for i in range(baris):
    for j in range(kolom):
      pembobotan_matriks[i][j] = matriks[i][j] * bobot[j]

  return np.array(pembobotan_matriks)

matriks_normalisasi_v = pembobotan_matriks(matriks_ternomalisasi)
matriks_normalisasi_v

array([[3.200922  , 0.79471941, 2.        , 0.91499142],
       [2.5607376 , 1.05962589, 2.        , 1.21998856],
       [2.5607376 , 1.05962589, 2.        , 0.91499142],
       [1.2803688 , 1.05962589, 2.        , 0.91499142]])

In [53]:
# List Himpunan Concordance Matriks
def get_himpunan_matriks(matriks, tipe):
  baris = len(matriks)
  kolom = len(matriks[0])

  himpunan_matriks = []

# List Coscordance
  for i in range(baris):
    for j in range(kolom):
      if i == j:
        continue

      if tipe.lower() == 'concordance':
        c = f'C{i+1}{j+1}'
      elif tipe.lower() == 'discordance':
        c = f'D{i+1}{j+1}'
      else:
        print('Tipe Tidak Dikenali!!!')
        return

      himpunan = get_himpunan(matriks, tipe, i, j)
      himpunan_c = {c: himpunan}

      himpunan_matriks.append(himpunan_c);

  for c in himpunan_matriks:
    print(c)

def get_himpunan(matriks, tipe, baris_a, baris_b):
  kolom = len(matriks[0])

  himpunan = []

  for j in range(kolom):

    if tipe.lower() == 'concordance':
      if matriks[baris_a][j] >= matriks[baris_b][j]:
        himpunan.append(j+1)
    elif tipe.lower() == 'discordance':
      if matriks[baris_a][j] < matriks[baris_b][j]:
        himpunan.append(j+1)
    else:
      print('Tipe Tidak Dikenali!!!')
      return

  return himpunan

get_himpunan_matriks(matriks_normalisasi_v, 'Concordance')

{'C12': [1, 3]}
{'C13': [1, 3, 4]}
{'C14': [1, 3, 4]}
{'C21': [2, 3, 4]}
{'C23': [1, 2, 3, 4]}
{'C24': [1, 2, 3, 4]}
{'C31': [2, 3, 4]}
{'C32': [1, 2, 3]}
{'C34': [1, 2, 3, 4]}
{'C41': [2, 3, 4]}
{'C42': [2, 3]}
{'C43': [2, 3, 4]}


In [54]:
# List Himpunan Discordance Matriks
get_himpunan_matriks(matriks_normalisasi_v, 'Discordance')

{'D12': [2, 4]}
{'D13': [2]}
{'D14': [2]}
{'D21': [1]}
{'D23': []}
{'D24': []}
{'D31': [1]}
{'D32': [4]}
{'D34': []}
{'D41': [1]}
{'D42': [1, 4]}
{'D43': [1]}


In [73]:
# Tabel Himpunan Concordance
def get_tabel_himpunan(matriks, tipe):
  baris = len(matriks)
  kolom = len(matriks[0])

  tabel_himpunan = [[0 for j in range(kolom)] for i in range(baris)]

  for i in range(baris):
    for j in range(kolom):
      if i != j:
        himpunan = get_himpunan(matriks, tipe, i, j);
        tabel_himpunan[i][j] = himpunan

  return np.array(tabel_himpunan, dtype=object)

tabel_himpunan_concordance = get_tabel_himpunan(matriks_normalisasi_v, 'Concordance')
tabel_himpunan_concordance

array([[0, list([1, 3]), list([1, 3, 4]), list([1, 3, 4])],
       [list([2, 3, 4]), 0, list([1, 2, 3, 4]), list([1, 2, 3, 4])],
       [list([2, 3, 4]), list([1, 2, 3]), 0, list([1, 2, 3, 4])],
       [list([2, 3, 4]), list([2, 3]), list([2, 3, 4]), 0]], dtype=object)

In [79]:
# Tabel Himpunan Discordance
tabel_himpunan_discordance = get_tabel_himpunan(matriks_normalisasi_v, 'Discordance')
tabel_himpunan_discordance

array([[0, list([2, 4]), list([2]), list([2])],
       [list([1]), 0, list([]), list([])],
       [list([1]), list([4]), 0, list([])],
       [list([1]), list([1, 4]), list([1]), 0]], dtype=object)

In [95]:
# Matriks Concordance
def buat_matriks_condis(tabel_himpunan, tipe, matriks=0):
  baris = len(tabel_himpunan)
  kolom = len(tabel_himpunan[0])

  matriks_concordance = np.zeros((baris, kolom))

  for i in range(baris):
    for j in range(kolom):
      if i != j:
        if tipe.lower() == 'concordance':
          matriks_concordance[i][j] = hitung_bobot_coscordance(tabel_himpunan[i][j])
        elif tipe.lower() == 'discordance':
          pembilang = max_himpunan(matriks, i, j, tabel_himpunan[i][j])
          penyebut = max_himpunan(matriks, i, j)
          matriks_concordance[i][j] = pembilang/penyebut
        else:
          print('Tipe Tidak Dikenali!!!')
          return


  return np.array(matriks_concordance)

def hitung_bobot_coscordance(list_himpunan):
  total_bobot = 0
  for i in list_himpunan:
    total_bobot += bobot[i-1]

  return total_bobot

matriks_concordance = buat_matriks_condis(tabel_himpunan_concordance, 'concordance')
matriks_concordance

array([[ 0.,  9., 11., 11.],
       [ 8.,  0., 13., 13.],
       [ 8., 11.,  0., 13.],
       [ 8.,  6.,  8.,  0.]])

In [96]:
# Matriks Discordance

def max_himpunan(matriks, baris_a, baris_b, list_himpunan = 0):
  kolom = len(matriks[0])

  list_selisih = []

  for j in range(kolom):
    if list_himpunan != 0:
      if not list_himpunan:
        return 0
      elif j + 1 in list_himpunan:
        list_selisih.append(abs(matriks[baris_a][j] - matriks[baris_b][j]))
    else:
      list_selisih.append(abs(matriks[baris_a][j] - matriks[baris_b][j]))

  return max(list_selisih)

matriks_discordance = buat_matriks_condis(tabel_himpunan_discordance, 'discordance', matriks_normalisasi_v)
matriks_discordance

array([[0.        , 0.47642076, 0.41379714, 0.13793238],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 1.        , 0.        , 0.        ],
       [1.        , 1.        , 1.        , 0.        ]])

In [101]:
# Menghitung Matrik Dominan Concordance dan Discordance
def hitung_matriks_dominan(matriks):
  baris = len(matriks)
  kolom = len(matriks[0])
  c = np.sum(matriks) / (baris * (baris-1))

  matriks_domain = np.zeros((baris, kolom))

  for i in range(baris):
    for j in range(kolom):
      if i != j:
        if matriks[i][j] >= c:
          matriks_domain[i][j] = 1

  return np.array(matriks_domain)

# Concordance
matriks_domain_concordance = hitung_matriks_dominan(matriks_concordance)
matriks_domain_concordance

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [102]:
# Discordance
matriks_domain_discordance = hitung_matriks_dominan(matriks_discordance)
matriks_domain_discordance

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [104]:
# Matriks Agregasi
def buat_matriks_agregasi(matriks_c, matriks_d):
  baris = len(matriks_c)
  kolom = len(matriks_c[0])

  matriks_agregasi = np.zeros((baris, kolom))

  for i in range(baris):
    for j in range(kolom):
      if i != j:
        matriks_agregasi[i][j] = int(matriks_c[i][j] * matriks_d[i][j])

  return np.array(matriks_agregasi)

matriks_agregasi = buat_matriks_agregasi(matriks_domain_concordance, matriks_discordance)
matriks_agregasi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.]])